//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int ID_Аренды { get; set; }
        public int ID_Арендатора { get; set; }
        public string Название { get; set; }
        public string ТЦ { get; set; }
        public int ID_Сотрудник { get; set; }
        public string C__Павильона { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> Начало_Аренды { get; set; }
        public Nullable<System.DateTime> Окончание_Аренды { get; set; }
        public string F10 { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
